# make this script executable and source it at end of ~/.bashrc

# ENV
export PROMPT_DIRTRIM=2

# system alias
alias c='clear'

# custom alias start

# alias code=codium
alias tmux='tmux -u'

# alias for xclip to copy to system clipboard
alias "xclip=tr -d '\n'|xclip -selection clipboard"

##
